
# The Basics of NumPy Arrays 

## What is numpy?
---

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

---

<h1 align='center'> Basics</h1>

*  NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:
    - `ndarray.ndim:` The number of axes(dimensions) of the array.
    - `ndarray.shape:` The dimension of array.For a matrix with x rows and y columns, shape will be (x,y).
    - `ndarray.size:` The total number of elements of the array or It is equal to the product of the elements of the `shape`.
    - `ndarray.dtype:` The type of the elements in the array. Additionally NumPy provides types of its own like- numpy.int32, numpy.int16, and numpy.float64.
    - `ndarray.itemsize:` The size in bytes of each element of the array. 
    - `ndarray.data:` The buffer containing the actual elements of the array. 

## Creating a NumPy array

In [2]:
# Import the numpy library and assign it the alias 'np'
import numpy as np

<font color='cadetblue' size='4'>Basic ndarray</font>


In [ ]:
# Create a 1-D numpy array with elements 1, 2, 3, and 4
np_array = np.array([1,2,3,4])

In [ ]:
type(np_array)

In [ ]:
# Display the data type of the elements in the numpy array
np_array.dtype

In [ ]:
# We can specify the type of data inside the array:
np_array = np.array([1,2,3,4], dtype=np.float32)

In [ ]:
np_array.dtype

<font size='4' font='italic'>Since NumPy arrays can contain only homogeneous datatypes, values will be upcast if the types do not match:</font>

In [ ]:
# Upcasting in NumPy arrays
# If we do not specify the type, numpy will choose it for us:
a = np.array([1,2,3.0,4])

In [ ]:
a.dtype

In [ ]:
print(a[0])

**NumPy arrays can be multi-dimensional too.**

In [ ]:
# Multi-dimensional arrays
# Create a 2D NumPy array (matrix) with two rows and four columns
a = np.array([[1,2,3,4],[5,6,7,8]])
a[1][2] = 45454
print(a[1][2])

<font color='cadetblue' size='4'>Array of zeros</font>


In [ ]:
# Cell: Array of zeros (1D)
# Create a 1D array of zeros with length 5
b = np.zeros(5)
print(b)

In [ ]:
# Cell: Array of zeros (2D)
# Create a 2D array of zeros with shape (3, 4)
k = np.zeros((3,4),dtype=np.int32)
k.dtype

In [ ]:
# Cell: Array of zeros (3D)
# Create a 3D array of zeros with shape (100, 512, 512)
np.zeros((100, 512, 512))

<font color='cadetblue' size='4'>Array of Ones</font>


In [ ]:
# Cell: Array of ones (1D)
# Create a 1D array of ones with length 5 and int32 type
np.ones(5, dtype=np.int32)

In [ ]:
# Cell: Array of ones (2D)
# Create a 2D array of ones with shape (3, 4)
np.ones((3, 4))

<font color='cadetblue' size='4'>Random number in array</font>

In [ ]:
# Cell: Random numbers in array
# Create a 2x3 array of random floats between 0 and 1
np.random.rand(2,3)

In [ ]:
# Cell: Array filled with a specific value
# Create a 2x3 array filled with the value 5
np.full((2,3), 5)

In [ ]:
aa = np.zeros((2,3)) + 5
print(aa)

<font color='cadetblue' size='4'>Sequence of numbers</font>

To create sequences of numbers, `NumPy` provides the arange function which is analogous to the Python built-in range, but returns an array.



In [ ]:
aa2 = np.ones((3,4)) * 5
print(aa2)

In [ ]:
# Cell: Sequence of numbers (arange)
# Create a 1D array with values from 10 to 25 (step 5)
np.arange(10, 31, 5)

In [ ]:
# Cell: Sequence of numbers with float step
# Create a 1D array with values from 0 to 2 (step 0.3)
np.arange(0, 2, 0.3)  # it accepts float arguments

<font color='cadetblue' size='4'>Evenly spaced ndarray</font>

**Another similar function is `np.linspace()`, but instead of step size, it takes in the number of samples that need to be retrieved from the interval. A point to note here is that the last number is included in the values returned unlike in the case of `np.arange()`.**

In [ ]:
# Cell: Evenly spaced numbers (linspace)
# Create 11 evenly spaced numbers between 0 and 1 (inclusive)
np.linspace(0, 1, 5)

<font color='cadetblue' size='4'>Identity Matrix in NumPy</font>

In [ ]:
# Cell: Identity matrix
# Create a 3x3 identity matrix (ones on main diagonal)
np.eye(3, k=0)

**NumPy gives you the flexibility to change the diagonal along which the values have to be 1s. You can either move it above the main diagonal:**

In [ ]:
# Cell: Identity matrix (above main diagonal)
# Create a 3x3 identity matrix with ones above the main diagonal
np.eye(3,k=1)

**Or move it below the main diagonal**

In [ ]:
# Cell: Identity matrix (below main diagonal)
# Create a 3x3 identity matrix with ones below the main diagonal
np.eye(3,k=-1)

<h1 align='center'>The Shape and Reshaping of NumPy Arrays</h1>

In [ ]:
b = np.arange(6)
b

In [ ]:
# Cell: Array shape, size, and manual size calculation
# Create a 2x3 array and print shape, size, rows, columns
b = np.arange(6)

a = np.arange(12).reshape(4,3)
print('Array:','\n',np.arange(12))
print('Array:', '\n', a)
print('Shape of the array:','\n',a.shape) # (2, 3)
print('Number of rows = ',a.shape[0])
print('Number of columns = ',a.shape[1])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

In [ ]:
k = np.zeros((100,20))
k.size

<font color='cadetblue' size='4'>Reshaping a NumPy array</font>

In [ ]:
# Cell: Reshape array
# Reshape a 1D array of 4 elements to 2x2
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

In [ ]:
# Cell: Reshape with -1
# Reshape a 1D array to 3 rows or 3 columns using -1
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3, -1))) # Numpy automatically calculate number of rows according to total items
print('Three columns :','\n',np.reshape(a,(-1, 3)))

<font color='cadetblue' size='4'>Flattening a NumPy array</font>

In [ ]:
# Cell: Flatten and ravel
# Flatten and ravel a 2x2 array and show shapes
a = np.ones((2,2))
b = a.flatten() # 1 x 4 -> 1D ARRAY
c = a.ravel() # 1 x 4 -> 1D array
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

In [ ]:
k = np.arange(10).reshape(-1,2)
print(k)
k1 = k.flatten()
print(k1)

In [ ]:
f1 = np.random.random((2,2,2))
print(f1)
print(f1.shape)
print(f1.size)
f2 = f1.flatten()
print("********************")
print(f2)
print(f2.size)
print(f2.shape)


In [ ]:
b[0] = 0
print(a)

**In this case, the change made was not reflected in the original array.**

In [ ]:
c[0] = 0
print(a)

**But here, the changed value is also reflected in the original ndarray.**

What is happening here is that `flatten()` creates a ***Deep copy*** of the ndarray while `ravel()` creates a ***Shallow copy*** of the ndarray.

> Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. Therefore, any changes made here will not be reflected in the original ndarray.

> A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object. So, definitely, any changes made to this ndarray will also be reflected in the original ndarray too.

<h1 align='center'>Maths with NumPy arrays<h1>

In [ ]:
# Cell: Array math (addition, ones)
# Create two arrays and add them element-wise
data = np.array([1,2]) # [1, 2] + [1, 1] = [2, 3]
ones = np.ones(2, dtype=int)
# test = np.zeros((200,200),dtype=int)
# print(type(test[0][0]))
a = 4565
b = 567
a1 = a + b

<class 'numpy.int64'>


In [4]:
# Cell: Addition
# Add two arrays and print result
add = data + ones # data = [1, 2] + [1, 1] = [2, 3]
print('Addition of two array','\n',add)

Addition of two array 
 [2 3]


In [11]:
# Cell: Subtraction, multiplication, division
# Subtract, multiply, and divide arrays element-wise
sub = data - ones
print('Subraction of two array:','\n',sub)

#Multiplication:
multi = data*data
print('Multiplication of two array','\n',multi)

#Division:u
div = data/data
print('Division by a constant','\n',div)
print(type(div[0]))

Subraction of two array: 
 [0 1]
Multiplication of two array 
 [1 4]
Division by a constant 
 [1. 1.]
<class 'numpy.float64'>


<font color='cadetblue' size='4'>Mean, Median and Standard deviation</font>

In [12]:
# Cell: Mean, std, median
# Calculate mean, standard deviation, and median of array
a = np.arange(5,15,2)
print('array',a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

array [ 5  7  9 11 13]
Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


<font color='cadetblue' size='4'>Min-Max values and their indexes</font>

In [17]:
# Cell: Min/Max values along axes
# Find min along columns and max along rows
a = np.array([[1,6], 
              [4,3],
              [9,2],
              [-2,7]])
# minimum along a column
print('Min :',np.min(a, axis=0))
# maximum along a row
print('Max :',np.max(a, axis=1))
print('max whole matrix', np.max(a))
max_ax1 = np.zeros(a.shape[0],dtype=int)
for i in range(a.shape[0]):
    max_ax1[i] = a[i][0]
    for j in range(a.shape[1]):
        if (max_ax1[i] < a[i][j]):
            max_ax1[i] = a[i][j]

print('my own max loop',max_ax1)


Min : [-2  2]
Max : [6 4 9 7]
max whole matrix 9
my own max loop [6 4 9 7]


In [18]:
# Cell: Min/Max indexes along axes
# Find indexes of min along columns and max along rows
a = np.array([[1, 6, 5],
              [4, 3, 7]])
# minimum along a column
print('Min :',np.argmin(a, axis=0))
# maximum along a row
print('Max :',np.argmax(a, axis=1))

Min : [0 1 0]
Max : [1 2]


<h1 align='center'>Sorting in NumPy arrays</h1>

In [19]:
# Cell: Sorting arrays
# Sort a 1D array and a 2D array along rows and columns
a = np.array([1,4,2,5,3,6,8,7,-9])
print('Sorted array:','\n',np.sort(a, kind='quicksort'))

b = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the row
print('Sort along row :','\n',np.sort(b, kind='mergesort',axis=1))
# sort along the column
print('Sort along column :','\n',np.sort(b, kind='mergesort',axis=0))

Sorted array: 
 [-9  1  2  3  4  5  6  7  8]
Sort along row : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along column : 
 [[5 2 3 4]
 [9 6 7 7]]


<h1 align='center'>Indexing and Slicing of NumPy array</h1>

<font color='cadetblue' size='4'>Slicing 1-D NumPy arrays</font>

In [ ]:
# Cell: Slicing 1D arrays
# Slice a 1D array from index 1 to 4
#initial position: included
#final position: excluded
a = np.array([1,2,3,4,5,6])
print(a[1:5])

In [ ]:
# Cell: Slicing with step
# Print every third element of array
print(a[::3])

In [ ]:
# Cell: Slicing with step size
# Print elements with step size 2, odd indices, etc.
#3rd: step size
print(a[:6:2])
print(a[1:6:])

<font color='cadetblue' size='4'>Slicing 2-D NumPy arrays</font>

In [ ]:
# Cell: Slicing 2D arrays
# Slice rows and columns of a 2D array
a = np.array([[1,2,3],
              [4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
#print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])

<h1 align='center'>Array Concatenation and Splitting</h1>

<font color='cadetblue' size='4'>Concatenation of arrays</font>

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument..

In [20]:
# Cell: Concatenation of arrays (1D)
# Concatenate two 1D arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [21]:
# Cell: Concatenate more than two arrays
# Concatenate three 1D arrays
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [22]:
# Cell: Concatenate 2D arrays along axis 0
# Concatenate two 2D arrays vertically
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
# Cell: Concatenate 2D arrays along axis 1
# Concatenate two 2D arrays horizontally
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [24]:
# Cell: Vertical and horizontal stacking
# Stack 1D and 2D arrays vertically and horizontally
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [25]:
# Cell: Horizontal stacking
# Stack a 2D array and a column vector horizontally
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
# Cell: Conditional selection
# Find indices of elements less than 5 in an array
a = [-1, 2, 3, 48, 5, 6, -7, 8, 9]
a = np.array(a)
print('index',np.where(a < 5))

# Show values less than 5
print('data,',a[np.where(a < 5)])

index (array([0, 1, 2, 6]),)
data, [-1  2  3 -7]


In [33]:
a = np.array([1, 2, -3, 4, 5])
mask = ((a < 3) & (a % 2 != 0))
print(mask)
a[mask]

[ True False  True False False]


array([ 1, -3])

In [ ]:
# Cell: Boolean indexing
# Select elements greater than 5 and even from array
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x[(x > 5) & (x % 2 == 0)]
#x > 5

Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

## References:

> https://numpy.org/doc/

> https://www.kaggle.com/learn/python